// Third curated batch — fills remaining high-frequency gaps across sexual health,
// paediatric infections, ophthalmology, neurology, MSK, mental health and more.
//
//   npm run import-extended2   (needs AWS creds)

import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, BatchWriteCommand } from '@aws-sdk/lib-dynamodb'
import type { ConditionEntry } from '../lib/types'

const TABLE = process.env.DDB_CONDITIONS_TABLE || 'MedicalConditions'
const region = process.env.AWS_REGION || 'us-east-1'
const doc = DynamoDBDocumentClient.from(new DynamoDBClient({ region }), { marshallOptions: { removeUndefinedValues: true } })

interface Spec { id: string; name: string; icd10: string; cks: string; category: string; symptoms: string[]; treatments: string[]; redFlags: string[] }

const E: Spec[] = [
  // Sexual health
  { id: 'A56', name: 'Chlamydia (genital)', icd10: 'A56.00', cks: 'chlamydia-uncomplicated-genital', category: 'Sexual health', symptoms: ['often asymptomatic', 'discharge', 'dysuria', 'pelvic pain', 'postcoital bleeding'], treatments: ['doxycycline', 'partner notification and treatment', 'STI screen', 'avoid sex until treated'], redFlags: ['pelvic pain with fever (PID)', 'pregnancy', 'testicular pain'] },
  { id: 'A54', name: 'Gonorrhoea', icd10: 'A54.00', cks: 'gonorrhoea', category: 'Sexual health', symptoms: ['purulent discharge', 'dysuria', 'often asymptomatic in women', 'rectal or throat involvement'], treatments: ['ceftriaxone (specialist guidance)', 'partner notification', 'test of cure', 'STI screen'], redFlags: ['disseminated infection (joint pain, rash)', 'PID', 'epididymo-orchitis'] },
  { id: 'A60', name: 'Genital herpes', icd10: 'A60.00', cks: 'herpes-simplex-genital', category: 'Sexual health', symptoms: ['painful genital blisters and ulcers', 'tingling prodrome', 'dysuria', 'tender lymph nodes'], treatments: ['oral antiviral', 'saline bathing and analgesia', 'partner discussion'], redFlags: ['urinary retention', 'immunocompromise', 'pregnancy near term'] },
  { id: 'A63', name: 'Anogenital warts', icd10: 'A63.0', cks: 'warts-anogenital', category: 'Sexual health', symptoms: ['painless genital lumps', 'cauliflower-like', 'occasional itch'], treatments: ['topical treatment or cryotherapy', 'reassurance', 'HPV vaccination advice'], redFlags: ['pigmented or bleeding lesion', 'immunosuppression'] },
  // Paediatric infections
  { id: 'B26', name: 'Mumps', icd10: 'B26.9', cks: 'mumps', category: 'Paediatrics', symptoms: ['parotid swelling', 'fever', 'malaise', 'pain on chewing'], treatments: ['supportive care and analgesia', 'isolate', 'notifiable disease'], redFlags: ['testicular pain (orchitis)', 'severe headache or neck stiffness (meningitis)', 'deafness'] },
  { id: 'A37', name: 'Whooping cough (pertussis)', icd10: 'A37.90', cks: 'whooping-cough', category: 'Paediatrics', symptoms: ['paroxysmal cough', 'inspiratory whoop', 'post-tussive vomiting', 'coughing fits worse at night'], treatments: ['macrolide antibiotic if early', 'notify and trace contacts', 'vaccination for prevention'], redFlags: ['apnoea or cyanosis in infants', 'feeding difficulty', 'seizures'] },
  { id: 'A38', name: 'Scarlet fever', icd10: 'A38.9', cks: 'scarlet-fever', category: 'Paediatrics', symptoms: ['fine sandpaper rash', 'strawberry tongue', 'sore throat', 'fever', 'flushed cheeks with perioral pallor'], treatments: ['penicillin (or alternative)', 'notifiable disease', 'fluids and antipyretics'], redFlags: ['signs of invasive group A strep', 'high persistent fever', 'rapid deterioration'] },
  { id: 'B08.3', name: 'Erythema infectiosum (slapped cheek)', icd10: 'B08.3', cks: 'parvovirus-b19-infection', category: 'Paediatrics', symptoms: ['bright red cheeks', 'lacy rash on limbs', 'mild fever', 'coryza'], treatments: ['supportive care', 'reassurance'], redFlags: ['pregnancy exposure', 'chronic haemolytic anaemia (aplastic crisis)', 'immunocompromise'] },
  { id: 'R56', name: 'Febrile seizure', icd10: 'R56.00', cks: 'febrile-seizure', category: 'Paediatrics', symptoms: ['generalised seizure during fever', 'age 6 months to 5 years', 'brief and self-limiting', 'post-ictal drowsiness'], treatments: ['protect from injury and recovery position', 'treat the underlying infection', 'antipyretics for comfort'], redFlags: ['seizure over 5 minutes', 'focal features', 'incomplete recovery', 'signs of meningitis'] },
  // Ophthalmology
  { id: 'H40', name: 'Acute angle-closure glaucoma', icd10: 'H40.219', cks: 'glaucoma', category: 'Ophthalmology', symptoms: ['sudden severe eye pain', 'red eye', 'haloes around lights', 'blurred vision', 'nausea and vomiting', 'fixed mid-dilated pupil'], treatments: ['emergency ophthalmology referral', 'IOP-lowering treatment', 'definitive laser iridotomy'], redFlags: ['acute visual loss', 'hard painful eye (sight-threatening emergency)'] },
  { id: 'H20', name: 'Anterior uveitis', icd10: 'H20.00', cks: 'uveitis', category: 'Ophthalmology', symptoms: ['painful red eye', 'photophobia', 'blurred vision', 'small or irregular pupil', 'watering'], treatments: ['urgent ophthalmology referral', 'topical steroids and cycloplegics (specialist)'], redFlags: ['visual loss', 'recurrent disease (associated systemic illness)'] },
  { id: 'H11', name: 'Subconjunctival haemorrhage', icd10: 'H11.30', cks: 'red-eye', category: 'Ophthalmology', symptoms: ['painless bright red patch on white of eye', 'normal vision', 'no discharge'], treatments: ['reassurance — resolves spontaneously', 'check blood pressure', 'review anticoagulation if recurrent'], redFlags: ['history of trauma', 'pain or visual change (other diagnosis)'] },
  { id: 'H00', name: 'Stye (hordeolum)', icd10: 'H00.019', cks: 'styes-meibomian-cysts', category: 'Ophthalmology', symptoms: ['tender red lump on eyelid margin', 'localised swelling', 'watering'], treatments: ['warm compresses', 'lid hygiene', 'usually self-resolving'], redFlags: ['spreading periorbital redness (cellulitis)', 'visual disturbance'] },
  // Neurology
  { id: 'G44.0', name: 'Cluster headache', icd10: 'G44.009', cks: 'cluster-headache', category: 'Neurology', symptoms: ['severe unilateral peri-orbital pain', 'lacrimation and nasal congestion', 'restlessness', 'attacks in clusters'], treatments: ['high-flow oxygen', 'subcutaneous or nasal triptan', 'specialist prophylaxis'], redFlags: ['first or atypical presentation', 'new focal neurology'] },
  { id: 'G35', name: 'Multiple sclerosis', icd10: 'G35', cks: 'multiple-sclerosis', category: 'Neurology', symptoms: ['relapsing neurological symptoms', 'optic neuritis', 'limb weakness or numbness', 'fatigue', 'bladder symptoms'], treatments: ['specialist neurology', 'disease-modifying therapy', 'symptom management', 'treat relapses with steroids'], redFlags: ['rapidly progressive deficit', 'cord compression features'] },
  { id: 'G45', name: 'Transient ischaemic attack', icd10: 'G45.9', cks: 'stroke-and-tia', category: 'Neurology', symptoms: ['transient focal weakness or speech disturbance', 'amaurosis fugax', 'full resolution within 24 hours'], treatments: ['urgent assessment and antiplatelet', 'manage vascular risk factors', 'carotid imaging'], redFlags: ['ongoing deficit (stroke)', 'crescendo TIAs', 'AF'] },
  { id: 'G25', name: 'Restless legs syndrome', icd10: 'G25.81', cks: 'restless-legs-syndrome', category: 'Neurology', symptoms: ['urge to move legs', 'worse at rest and in evening', 'relieved by movement', 'disturbed sleep'], treatments: ['check and replace iron', 'sleep and lifestyle measures', 'dopaminergic agents if severe'], redFlags: ['focal neurology', 'features of peripheral neuropathy'] },
  // ENT
  { id: 'H61', name: 'Earwax impaction', icd10: 'H61.20', cks: 'earwax', category: 'ENT', symptoms: ['reduced hearing', 'blocked ear', 'mild discomfort', 'tinnitus'], treatments: ['softening drops', 'irrigation or microsuction', 'avoid cotton buds'], redFlags: ['sudden hearing loss', 'pain with discharge (infection)', 'vertigo'] },
  { id: 'H93', name: 'Tinnitus', icd10: 'H93.19', cks: 'tinnitus', category: 'ENT', symptoms: ['ringing or buzzing in ears', 'worse in quiet', 'may affect sleep or concentration'], treatments: ['reassurance and sound therapy', 'treat underlying cause', 'hearing aids if hearing loss'], redFlags: ['unilateral or pulsatile tinnitus', 'associated neurology or hearing loss'] },
  // GI
  { id: 'K60', name: 'Anal fissure', icd10: 'K60.2', cks: 'anal-fissure', category: 'Gastroenterology', symptoms: ['sharp pain on defecation', 'bright red blood on wiping', 'anal spasm', 'often after constipation'], treatments: ['soften stool with fibre and fluids', 'topical GTN or diltiazem', 'analgesia'], redFlags: ['atypical or lateral fissures (consider IBD/infection)', 'mass or weight loss'] },
  { id: 'E73', name: 'Lactose intolerance', icd10: 'E73.9', cks: 'lactose-intolerance', category: 'Gastroenterology', symptoms: ['bloating', 'diarrhoea after dairy', 'cramps', 'flatulence'], treatments: ['reduce lactose intake', 'lactase supplements', 'ensure calcium intake'], redFlags: ['weight loss', 'blood in stool', 'nocturnal symptoms (alternative diagnosis)'] },
  // Endocrine
  { id: 'E27', name: "Addison's disease (adrenal insufficiency)", icd10: 'E27.1', cks: 'addisons-disease', category: 'Endocrinology', symptoms: ['fatigue', 'weight loss', 'hyperpigmentation', 'postural dizziness', 'salt craving', 'nausea'], treatments: ['steroid replacement (hydrocortisone, fludrocortisone)', 'sick-day rules', 'emergency steroid card'], redFlags: ['vomiting, hypotension and collapse (adrenal crisis)', 'hyponatraemia'] },
  // MSK / rheumatology
  { id: 'M77', name: 'Tennis elbow (lateral epicondylitis)', icd10: 'M77.10', cks: 'tennis-elbow', category: 'Musculoskeletal', symptoms: ['pain over lateral elbow', 'worse on gripping', 'tender lateral epicondyle', 'pain on wrist extension'], treatments: ['relative rest and load management', 'analgesia and physiotherapy', 'consider injection if persistent'], redFlags: ['neurological symptoms', 'trauma or swelling'] },
  { id: 'M65', name: "De Quervain's tenosynovitis", icd10: 'M65.4', cks: 'tenosynovitis', category: 'Musculoskeletal', symptoms: ['pain at radial wrist', 'worse on thumb movement', 'swelling over the styloid', 'positive Finkelstein test'], treatments: ['thumb spica splint', 'analgesia', 'corticosteroid injection if needed'], redFlags: ['signs of infection', 'numbness'] },
  { id: 'M45', name: 'Ankylosing spondylitis', icd10: 'M45.9', cks: 'ankylosing-spondylitis', category: 'Rheumatology', symptoms: ['inflammatory back pain', 'morning stiffness over 30 minutes', 'improves with exercise', 'buttock pain', 'young adult'], treatments: ['exercise and physiotherapy', 'NSAID', 'biologics under specialist care'], redFlags: ['acute eye pain (uveitis)', 'progressive neurology', 'cardiac or pulmonary involvement'] },
  // Mental health
  { id: 'F42', name: 'Obsessive-compulsive disorder', icd10: 'F42.9', cks: 'obsessive-compulsive-disorder', category: 'Mental health', symptoms: ['intrusive obsessions', 'compulsive rituals', 'marked distress', 'time-consuming behaviours'], treatments: ['CBT with exposure and response prevention', 'SSRI', 'self-help resources'], redFlags: ['suicidal ideation', 'severe functional impairment'] },
  { id: 'F43', name: 'Post-traumatic stress disorder', icd10: 'F43.10', cks: 'post-traumatic-stress-disorder', category: 'Mental health', symptoms: ['flashbacks and nightmares', 'avoidance', 'hypervigilance', 'emotional numbing', 'after trauma'], treatments: ['trauma-focused CBT or EMDR', 'consider SSRI', 'avoid routine debriefing'], redFlags: ['suicidal ideation', 'psychosis', 'substance misuse'] },
  { id: 'F31', name: 'Bipolar disorder', icd10: 'F31.9', cks: 'bipolar-disorder', category: 'Mental health', symptoms: ['episodes of elevated mood and overactivity', 'reduced need for sleep', 'grandiosity', 'alternating with depression'], treatments: ['specialist mental health care', 'mood stabiliser', 'psychological support'], redFlags: ['risk to self or others', 'psychosis', 'severe mania'] },
  { id: 'F50', name: 'Eating disorder (anorexia nervosa)', icd10: 'F50.00', cks: 'eating-disorders', category: 'Mental health', symptoms: ['restricted eating', 'fear of weight gain', 'distorted body image', 'low weight', 'amenorrhoea'], treatments: ['specialist eating-disorder service', 'medical monitoring', 'psychological therapy'], redFlags: ['very low or rapidly falling weight', 'bradycardia or electrolyte disturbance', 'suicidal ideation'] },
  { id: 'F10', name: 'Alcohol-use disorder', icd10: 'F10.10', cks: 'alcohol-problem-drinking', category: 'Mental health', symptoms: ['craving', 'loss of control over drinking', 'tolerance', 'withdrawal symptoms', 'neglect of responsibilities'], treatments: ['brief intervention and support', 'assisted withdrawal where needed', 'relapse-prevention medication and counselling'], redFlags: ['withdrawal seizures or delirium tremens', 'jaundice or GI bleeding', 'suicidal ideation'] },
  // Dermatology (non-image)
  { id: 'L73', name: 'Hidradenitis suppurativa', icd10: 'L73.2', cks: 'hidradenitis-suppurativa', category: 'Dermatology', symptoms: ['recurrent painful nodules in axillae or groin', 'abscesses', 'sinus tracts', 'scarring'], treatments: ['lifestyle (smoking, weight)', 'topical/oral antibiotics', 'specialist dermatology for severe disease'], redFlags: ['extensive disease with scarring', 'signs of systemic infection'] },
  { id: 'L40.5', name: 'Psoriatic arthritis', icd10: 'L40.50', cks: 'psoriatic-arthritis', category: 'Rheumatology', symptoms: ['joint pain and swelling with psoriasis', 'dactylitis', 'nail changes', 'morning stiffness', 'enthesitis'], treatments: ['NSAID for symptoms', 'DMARDs or biologics', 'specialist rheumatology'], redFlags: ['rapid joint destruction', 'septic joint'] },
  // Respiratory / immunology
  { id: 'D86', name: 'Sarcoidosis', icd10: 'D86.9', cks: 'sarcoidosis', category: 'Respiratory', symptoms: ['dry cough', 'breathlessness', 'fatigue', 'erythema nodosum', 'joint pains'], treatments: ['observation in mild disease', 'corticosteroids if organ-threatening', 'specialist follow-up'], redFlags: ['cardiac or neurological involvement', 'significant lung impairment', 'hypercalcaemia'] },
  // Cardiology / vascular
  { id: 'I83', name: 'Varicose veins', icd10: 'I83.90', cks: 'varicose-veins', category: 'Vascular', symptoms: ['visible dilated leg veins', 'aching or heaviness', 'worse on standing', 'ankle swelling'], treatments: ['compression and leg elevation', 'weight and activity advice', 'referral for endovenous treatment if symptomatic'], redFlags: ['skin changes or ulceration', 'bleeding varicosity', 'signs of DVT'] },
  { id: 'I95', name: 'Postural (orthostatic) hypotension', icd10: 'I95.1', cks: 'blood-pressure-low', category: 'Cardiology', symptoms: ['light-headedness on standing', 'blurred vision', 'falls', 'fatigue'], treatments: ['review medications', 'hydration and slow position changes', 'compression stockings'], redFlags: ['syncope with injury', 'new neurology', 'GI bleeding causing hypovolaemia'] },
  // Women's / men's health
  { id: 'N61', name: 'Mastitis', icd10: 'N61.0', cks: 'mastitis-and-breast-abscess', category: "Women's health", symptoms: ['painful red wedge-shaped area of breast', 'fever', 'flu-like symptoms', 'often during breastfeeding'], treatments: ['continue effective milk removal', 'analgesia', 'antibiotics if not improving or systemically unwell'], redFlags: ['fluctuant swelling (abscess)', 'sepsis', 'non-lactational mass (exclude inflammatory cancer)'] },
  { id: 'O14', name: 'Pre-eclampsia', icd10: 'O14.90', cks: 'hypertension-in-pregnancy', category: "Women's health", symptoms: ['hypertension after 20 weeks', 'proteinuria', 'headache', 'visual disturbance', 'epigastric pain', 'swelling'], treatments: ['urgent obstetric assessment', 'antihypertensives', 'monitoring and timely delivery'], redFlags: ['severe headache or visual symptoms', 'seizure (eclampsia)', 'reduced fetal movements'] },
  { id: 'N45', name: 'Epididymo-orchitis', icd10: 'N45.4', cks: 'scrotal-pain-and-swelling', category: 'Urology', symptoms: ['gradual onset scrotal pain and swelling', 'tenderness', 'dysuria', 'fever'], treatments: ['antibiotics per likely cause', 'analgesia and scrotal support', 'STI screen if relevant'], redFlags: ['sudden severe pain in young male (testicular torsion — emergency)', 'abscess', 'systemic sepsis'] },
  { id: 'N44', name: 'Testicular torsion', icd10: 'N44.00', cks: 'scrotal-pain-and-swelling', category: 'Urology', symptoms: ['sudden severe testicular pain', 'often young male', 'nausea and vomiting', 'high-riding testis', 'absent cremasteric reflex'], treatments: ['EMERGENCY surgical exploration within hours', 'urgent urology referral', 'do not delay for imaging'], redFlags: ['any acute testicular pain is torsion until proven otherwise'] },
]

async function main() {
  const now = new Date().toISOString()
  const items: ConditionEntry[] = E.map((s) => ({
    conditionId: s.id, name: s.name, icd10Code: s.icd10, category: s.category,
    symptoms: s.symptoms, treatments: s.treatments, redFlags: s.redFlags,
    citations: [{ id: `${s.id}-cks`, title: `${s.name} — NICE Clinical Knowledge Summaries`, source: 'NICE CKS', url: `https://cks.nice.org.uk/topics/${s.cks}/`, identifier: 'NICE CKS' }],
    source: 'curated', prior: 1.0, updatedAt: now,
  }))
  for (let i = 0; i < items.length; i += 25) {
    await doc.send(new BatchWriteCommand({ RequestItems: { [TABLE]: items.slice(i, i + 25).map((Item) => ({ PutRequest: { Item } })) } }))
  }
  console.log(`Done. ${items.length} conditions written.`)
}

main().catch((e) => { console.error('import-extended2 failed:', e?.message || e); process.exit(1) })
