// Large multi-specialty batch of curated conditions (treatments + red flags +
// NICE CKS citation). Broadens common-case coverage well beyond primary-care basics.
//
//   npm run import-extended   (needs AWS creds)

import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, BatchWriteCommand } from '@aws-sdk/lib-dynamodb'
import type { ConditionEntry } from '../lib/types'

const TABLE = process.env.DDB_CONDITIONS_TABLE || 'MedicalConditions'
const region = process.env.AWS_REGION || 'us-east-1'
const doc = DynamoDBDocumentClient.from(new DynamoDBClient({ region }), { marshallOptions: { removeUndefinedValues: true } })

interface Spec { id: string; name: string; icd10: string; cks: string; category: string; symptoms: string[]; treatments: string[]; redFlags: string[] }

const E: Spec[] = [
  // Cardiology / vascular
  { id: 'I48', name: 'Atrial fibrillation', icd10: 'I48.91', cks: 'atrial-fibrillation', category: 'Cardiology', symptoms: ['palpitations', 'irregularly irregular pulse', 'breathlessness', 'fatigue', 'dizziness'], treatments: ['rate or rhythm control', 'anticoagulation per CHA2DS2-VASc', 'treat reversible causes'], redFlags: ['haemodynamic instability', 'chest pain', 'syncope', 'signs of stroke'] },
  { id: 'I50', name: 'Chronic heart failure', icd10: 'I50.9', cks: 'heart-failure-chronic', category: 'Cardiology', symptoms: ['exertional breathlessness', 'orthopnoea', 'ankle swelling', 'fatigue', 'paroxysmal nocturnal dyspnoea'], treatments: ['ACE inhibitor and beta-blocker', 'diuretic for congestion', 'manage comorbidities'], redFlags: ['acute pulmonary oedema', 'rest breathlessness', 'hypotension'] },
  { id: 'I20', name: 'Stable angina', icd10: 'I20.9', cks: 'angina', category: 'Cardiology', symptoms: ['central chest tightness on exertion', 'relieved by rest', 'radiation to arm or jaw', 'breathlessness'], treatments: ['GTN spray for attacks', 'beta-blocker or calcium-channel blocker', 'secondary prevention (statin, antiplatelet)'], redFlags: ['pain at rest or worsening (unstable angina)', 'prolonged pain (possible MI)'] },
  { id: 'I82', name: 'Deep vein thrombosis', icd10: 'I82.409', cks: 'dvt-deep-vein-thrombosis', category: 'Vascular', symptoms: ['unilateral calf swelling', 'leg pain', 'warmth', 'redness', 'tenderness along deep veins'], treatments: ['anticoagulation', 'assess with Wells score and D-dimer', 'compression as advised'], redFlags: ['chest pain or breathlessness (PE)', 'massively swollen white or blue leg'] },
  { id: 'I73', name: 'Peripheral arterial disease', icd10: 'I73.9', cks: 'peripheral-arterial-disease', category: 'Vascular', symptoms: ['intermittent claudication', 'calf pain on walking', 'cold pale feet', 'absent pulses', 'poor wound healing'], treatments: ['supervised exercise', 'smoking cessation', 'statin and antiplatelet', 'manage risk factors'], redFlags: ['rest pain', 'ulceration or gangrene (critical limb ischaemia)'] },

  // Respiratory
  { id: 'J20', name: 'Acute bronchitis', icd10: 'J20.9', cks: 'chest-infections-adult', category: 'Respiratory', symptoms: ['cough often productive', 'preceding cold', 'wheeze', 'chest discomfort', 'usually no fever'], treatments: ['self-care and fluids', 'most are viral — antibiotics rarely needed', 'simple analgesia'], redFlags: ['breathlessness at rest', 'high fever', 'focal chest signs (pneumonia)', 'haemoptysis'] },
  { id: 'J21', name: 'Bronchiolitis (infant)', icd10: 'J21.9', cks: 'bronchiolitis', category: 'Paediatrics', symptoms: ['coryza then cough', 'wheeze or crackles', 'poor feeding', 'fast breathing', 'under 2 years'], treatments: ['supportive care and hydration', 'monitor feeding and breathing', 'oxygen if hypoxic'], redFlags: ['grunting or marked recession', 'apnoea', 'poor feeding under 50% normal', 'cyanosis'] },
  { id: 'J05', name: 'Croup', icd10: 'J05.0', cks: 'croup', category: 'Paediatrics', symptoms: ['barking cough', 'stridor', 'hoarse voice', 'coryza', 'worse at night'], treatments: ['single dose oral dexamethasone', 'keep child calm', 'most are mild and self-limiting'], redFlags: ['stridor at rest', 'drooling', 'cyanosis', 'severe recession or exhaustion'] },
  { id: 'G47.3', name: 'Obstructive sleep apnoea', icd10: 'G47.33', cks: 'obstructive-sleep-apnoea-syndrome', category: 'Respiratory', symptoms: ['loud snoring', 'witnessed apnoeas', 'daytime sleepiness', 'morning headache', 'poor concentration'], treatments: ['weight loss and lifestyle', 'CPAP for moderate–severe', 'avoid alcohol and sedatives'], redFlags: ['falling asleep while driving', 'resistant hypertension', 'right heart failure'] },

  // GI
  { id: 'K27', name: 'Peptic ulcer disease', icd10: 'K27.9', cks: 'dyspepsia-proven-peptic-ulcer', category: 'Gastroenterology', symptoms: ['epigastric pain', 'relation to meals', 'nausea', 'bloating', 'early satiety'], treatments: ['proton pump inhibitor', 'test and treat H. pylori', 'stop NSAIDs if possible'], redFlags: ['haematemesis or melaena', 'weight loss', 'dysphagia', 'persistent vomiting'] },
  { id: 'K90', name: 'Coeliac disease', icd10: 'K90.0', cks: 'coeliac-disease', category: 'Gastroenterology', symptoms: ['chronic diarrhoea', 'bloating', 'weight loss', 'fatigue', 'iron-deficiency anaemia'], treatments: ['lifelong gluten-free diet', 'correct deficiencies', 'dietitian input'], redFlags: ['severe malnutrition', 'refractory symptoms despite diet'] },
  { id: 'K57', name: 'Diverticular disease', icd10: 'K57.30', cks: 'diverticular-disease', category: 'Gastroenterology', symptoms: ['left lower abdominal pain', 'altered bowel habit', 'bloating', 'fever if diverticulitis'], treatments: ['high-fibre diet', 'analgesia avoiding NSAIDs', 'antibiotics for acute diverticulitis if indicated'], redFlags: ['severe pain with peritonism', 'rectal bleeding', 'high fever (perforation/abscess)'] },
  { id: 'K59', name: 'Constipation', icd10: 'K59.00', cks: 'constipation', category: 'Gastroenterology', symptoms: ['infrequent hard stools', 'straining', 'incomplete emptying', 'abdominal discomfort', 'bloating'], treatments: ['fibre and fluids', 'laxatives (bulk-forming, osmotic, stimulant)', 'toileting routine'], redFlags: ['rectal bleeding', 'weight loss', 'new change in bowel habit over age 50', 'anaemia'] },
  { id: 'K64', name: 'Haemorrhoids', icd10: 'K64.9', cks: 'haemorrhoids', category: 'Gastroenterology', symptoms: ['bright red rectal bleeding on wiping', 'anal itch', 'perianal lump', 'discomfort on defecation'], treatments: ['increase fibre and fluids', 'topical preparations', 'banding or surgery if persistent'], redFlags: ['dark blood or mixed with stool', 'weight loss', 'change in bowel habit (exclude cancer)'] },
  { id: 'K35', name: 'Acute appendicitis', icd10: 'K35.80', cks: 'appendicitis', category: 'Surgery', symptoms: ['central pain shifting to right iliac fossa', 'anorexia', 'nausea', 'low-grade fever', 'tenderness at McBurney point'], treatments: ['urgent surgical assessment', 'analgesia and IV fluids', 'appendicectomy'], redFlags: ['generalised peritonitis', 'high fever and tachycardia (perforation)'] },
  { id: 'K50', name: "Crohn's disease", icd10: 'K50.90', cks: 'crohns-disease', category: 'Gastroenterology', symptoms: ['chronic diarrhoea', 'abdominal pain', 'weight loss', 'fatigue', 'mouth ulcers', 'perianal disease'], treatments: ['induce remission (steroids/biologics)', 'maintenance immunomodulators', 'specialist gastroenterology care'], redFlags: ['bowel obstruction', 'severe bleeding', 'toxic megacolon', 'abscess or fistula'] },
  { id: 'K51', name: 'Ulcerative colitis', icd10: 'K51.90', cks: 'ulcerative-colitis', category: 'Gastroenterology', symptoms: ['bloody diarrhoea', 'urgency', 'tenesmus', 'lower abdominal pain', 'fatigue'], treatments: ['aminosalicylates', 'steroids for flares', 'specialist follow-up'], redFlags: ['severe flare (frequent bloody stools, fever, tachycardia)', 'toxic megacolon'] },

  // Endocrine / metabolic
  { id: 'E10', name: 'Type 1 diabetes mellitus', icd10: 'E10.9', cks: 'diabetes-type-1', category: 'Endocrinology', symptoms: ['polyuria', 'polydipsia', 'weight loss', 'fatigue', 'often younger onset'], treatments: ['insulin replacement', 'structured education and glucose monitoring', 'dietitian support'], redFlags: ['vomiting with high glucose and ketones (DKA)', 'drowsiness', 'abdominal pain'] },
  { id: 'E05', name: 'Hyperthyroidism', icd10: 'E05.90', cks: 'hyperthyroidism', category: 'Endocrinology', symptoms: ['weight loss', 'heat intolerance', 'palpitations', 'tremor', 'anxiety', 'diarrhoea'], treatments: ['antithyroid drugs (carbimazole)', 'beta-blocker for symptoms', 'consider radioiodine or surgery'], redFlags: ['fever, agitation and tachyarrhythmia (thyroid storm)', 'new AF'] },
  { id: 'E66', name: 'Obesity', icd10: 'E66.9', cks: 'obesity', category: 'Endocrinology', symptoms: ['raised BMI', 'central adiposity', 'breathlessness on exertion', 'joint pain'], treatments: ['diet and physical activity', 'behavioural support', 'pharmacotherapy or surgery for eligible patients'], redFlags: ['features of secondary cause', 'obesity hypoventilation', 'severe OSA'] },
  { id: 'E55', name: 'Vitamin D deficiency', icd10: 'E55.9', cks: 'vitamin-d-deficiency', category: 'Endocrinology', symptoms: ['bone or muscle aches', 'fatigue', 'proximal muscle weakness', 'low mood'], treatments: ['vitamin D supplementation', 'address dietary and sunlight factors'], redFlags: ['bone pain with fractures (osteomalacia)', 'symptomatic hypocalcaemia'] },
  { id: 'E28', name: 'Polycystic ovary syndrome', icd10: 'E28.2', cks: 'polycystic-ovary-syndrome', category: 'Endocrinology', symptoms: ['irregular periods', 'hirsutism', 'acne', 'weight gain', 'subfertility'], treatments: ['lifestyle and weight management', 'combined pill for cycle/hirsutism', 'metabolic risk screening'], redFlags: ['rapid virilisation', 'prolonged amenorrhoea (endometrial risk)'] },

  // Renal / urology
  { id: 'N40', name: 'Benign prostatic hyperplasia', icd10: 'N40.0', cks: 'luts-in-men', category: 'Urology', symptoms: ['weak urinary stream', 'frequency', 'nocturia', 'hesitancy', 'incomplete emptying'], treatments: ['lifestyle and bladder advice', 'alpha-blocker', '5-alpha-reductase inhibitor for large prostate'], redFlags: ['acute urinary retention', 'haematuria', 'recurrent UTI', 'renal impairment'] },
  { id: 'N52', name: 'Erectile dysfunction', icd10: 'N52.9', cks: 'erectile-dysfunction', category: 'Urology', symptoms: ['difficulty achieving or maintaining erection', 'reduced libido', 'relationship distress'], treatments: ['address cardiovascular risk', 'PDE5 inhibitor', 'psychological support'], redFlags: ['sudden onset with chest pain on exertion (cardiac marker)', 'priapism'] },
  { id: 'N20', name: 'Renal / ureteric colic (kidney stones)', icd10: 'N20.0', cks: 'renal-or-ureteric-colic-acute', category: 'Urology', symptoms: ['severe loin to groin pain', 'cannot get comfortable', 'haematuria', 'nausea', 'vomiting'], treatments: ['NSAID analgesia', 'fluids and antiemetic', 'imaging and urology referral'], redFlags: ['fever with obstruction (infected stone — emergency)', 'single kidney', 'anuria'] },
  { id: 'N18', name: 'Chronic kidney disease', icd10: 'N18.9', cks: 'chronic-kidney-disease', category: 'Nephrology', symptoms: ['often asymptomatic', 'fatigue', 'oedema', 'nocturia', 'reduced eGFR'], treatments: ['control BP and diabetes', 'ACE inhibitor/ARB if proteinuria', 'avoid nephrotoxins', 'monitor eGFR'], redFlags: ['rapidly rising creatinine', 'hyperkalaemia', 'fluid overload', 'uraemic symptoms'] },

  // Women's health
  { id: 'N92', name: 'Heavy menstrual bleeding', icd10: 'N92.0', cks: 'menorrhagia', category: "Women's health", symptoms: ['heavy periods', 'flooding or clots', 'prolonged bleeding', 'fatigue', 'anaemia'], treatments: ['levonorgestrel intrauterine system', 'tranexamic acid or NSAID', 'hormonal options', 'treat anaemia'], redFlags: ['postcoital or intermenstrual bleeding', 'postmenopausal bleeding', 'pelvic mass'] },
  { id: 'N94', name: 'Dysmenorrhoea', icd10: 'N94.6', cks: 'dysmenorrhoea', category: "Women's health", symptoms: ['cramping lower abdominal pain with periods', 'radiates to back or thighs', 'nausea'], treatments: ['NSAID', 'hormonal contraception', 'heat and self-care'], redFlags: ['pain with abnormal bleeding or discharge', 'deep dyspareunia (consider secondary cause)'] },
  { id: 'N95', name: 'Menopause', icd10: 'N95.1', cks: 'menopause', category: "Women's health", symptoms: ['hot flushes', 'night sweats', 'irregular then absent periods', 'mood changes', 'vaginal dryness'], treatments: ['HRT if appropriate', 'vaginal oestrogen for local symptoms', 'lifestyle measures'], redFlags: ['postmenopausal bleeding', 'unexplained weight loss'] },
  { id: 'N76', name: 'Bacterial vaginosis', icd10: 'N76.0', cks: 'bacterial-vaginosis', category: "Women's health", symptoms: ['thin grey-white discharge', 'fishy odour', 'usually no soreness or itch'], treatments: ['oral or vaginal metronidazole', 'avoid douching'], redFlags: ['pelvic pain or fever (consider PID)', 'pregnancy complications'] },
  { id: 'N73', name: 'Pelvic inflammatory disease', icd10: 'N73.9', cks: 'pelvic-inflammatory-disease', category: "Women's health", symptoms: ['lower abdominal pain', 'abnormal discharge', 'deep dyspareunia', 'fever', 'intermenstrual bleeding'], treatments: ['empirical antibiotics', 'test and treat partners', 'STI screening'], redFlags: ['severe pain with peritonism (abscess)', 'pregnancy (exclude ectopic)'] },
  { id: 'N80', name: 'Endometriosis', icd10: 'N80.9', cks: 'endometriosis', category: "Women's health", symptoms: ['chronic pelvic pain', 'painful periods', 'deep dyspareunia', 'subfertility', 'cyclical bowel/bladder symptoms'], treatments: ['analgesia', 'hormonal suppression', 'specialist referral and laparoscopy'], redFlags: ['acute severe pain (ovarian torsion/rupture)', 'bowel obstruction symptoms'] },

  // Paediatrics
  { id: 'R50', name: 'Febrile child', icd10: 'R50.9', cks: 'feverish-children-management', category: 'Paediatrics', symptoms: ['fever', 'irritability', 'reduced feeding', 'lethargy', 'variable focus'], treatments: ['antipyretics for distress', 'fluids', 'safety-net and review', 'assess using traffic-light system'], redFlags: ['non-blanching rash', 'lethargy or not responding', 'fast breathing', 'under 3 months with fever'] },

  // Neurology
  { id: 'G51', name: "Bell's palsy", icd10: 'G51.0', cks: 'bells-palsy', category: 'Neurology', symptoms: ['acute unilateral facial weakness', 'unable to raise eyebrow', 'drooping mouth', 'eye cannot close'], treatments: ['oral prednisolone within 72h', 'eye protection (lubricants, taping)', 'most recover'], redFlags: ['forehead spared (suggests stroke)', 'other neurology', 'bilateral weakness', 'vesicles (Ramsay Hunt)'] },
  { id: 'G50', name: 'Trigeminal neuralgia', icd10: 'G50.0', cks: 'trigeminal-neuralgia', category: 'Neurology', symptoms: ['brief electric-shock facial pain', 'triggered by touch or chewing', 'unilateral', 'in trigeminal distribution'], treatments: ['carbamazepine', 'specialist referral if refractory'], redFlags: ['sensory loss', 'other cranial neuropathy', 'age under 40 (consider MS)'] },
  { id: 'G40', name: 'Epilepsy', icd10: 'G40.909', cks: 'epilepsy', category: 'Neurology', symptoms: ['recurrent seizures', 'loss of awareness', 'convulsions', 'post-ictal confusion', 'aura'], treatments: ['anti-seizure medication', 'safety advice and driving rules', 'specialist neurology'], redFlags: ['seizure over 5 minutes (status epilepticus)', 'first seizure', 'focal neurology'] },
  { id: 'M54.3', name: 'Sciatica (lumbar radiculopathy)', icd10: 'M54.30', cks: 'sciatica-lumbar-radiculopathy', category: 'Neurology', symptoms: ['leg pain below the knee', 'worse than back pain', 'tingling or numbness', 'dermatomal pattern'], treatments: ['stay active', 'analgesia', 'physiotherapy', 'consider neuropathic agents'], redFlags: ['saddle anaesthesia or bladder/bowel dysfunction (cauda equina)', 'bilateral or progressive weakness'] },
  { id: 'G56', name: 'Carpal tunnel syndrome', icd10: 'G56.00', cks: 'carpal-tunnel-syndrome', category: 'Neurology', symptoms: ['numbness and tingling in thumb and fingers', 'worse at night', 'weak grip', 'shaking hand relieves it'], treatments: ['wrist splint', 'activity modification', 'corticosteroid injection or surgery if severe'], redFlags: ['thenar wasting', 'constant numbness (axonal loss)'] },
  { id: 'H81', name: 'Benign paroxysmal positional vertigo', icd10: 'H81.10', cks: 'vertigo', category: 'Neurology', symptoms: ['brief spinning on head movement', 'triggered by rolling over', 'nausea', 'no hearing loss'], treatments: ['Epley manoeuvre', 'reassurance', 'vestibular exercises'], redFlags: ['new headache or neurology', 'hearing loss', 'continuous vertigo (central cause)'] },

  // ENT / eye
  { id: 'H60', name: 'Otitis externa', icd10: 'H60.90', cks: 'otitis-externa', category: 'ENT', symptoms: ['ear pain', 'itch', 'discharge', 'pain on moving tragus', 'reduced hearing'], treatments: ['topical antibiotic/steroid drops', 'keep ear dry', 'aural toilet'], redFlags: ['severe pain in diabetic or immunocompromised (malignant otitis externa)', 'facial weakness'] },
  { id: 'R04', name: 'Epistaxis (nosebleed)', icd10: 'R04.0', cks: 'epistaxis-nosebleeds', category: 'ENT', symptoms: ['bleeding from nose', 'usually unilateral', 'often anterior septum'], treatments: ['lean forward and pinch soft part 10–15 min', 'topical measures', 'cautery or packing if persistent'], redFlags: ['heavy bleeding not controlled', 'anticoagulant use', 'haemodynamic compromise'] },
  { id: 'H04', name: 'Dry eye disease', icd10: 'H04.123', cks: 'dry-eye-disease', category: 'Ophthalmology', symptoms: ['gritty burning eyes', 'fluctuating vision', 'watering (reflex)', 'worse with screens'], treatments: ['lubricating drops', 'lid hygiene', 'reduce screen strain'], redFlags: ['significant pain', 'marked redness', 'vision loss (other diagnosis)'] },
  { id: 'H01', name: 'Blepharitis', icd10: 'H01.009', cks: 'blepharitis', category: 'Ophthalmology', symptoms: ['sore crusty eyelid margins', 'grittiness', 'flaking at lash base', 'worse in mornings'], treatments: ['warm compresses and lid hygiene', 'lubricants', 'topical antibiotic if needed'], redFlags: ['loss of lashes or distorted lid (consider malignancy)', 'severe pain or visual loss'] },

  // MSK / rheumatology
  { id: 'M06', name: 'Rheumatoid arthritis', icd10: 'M06.9', cks: 'rheumatoid-arthritis', category: 'Rheumatology', symptoms: ['symmetrical small-joint pain', 'early morning stiffness over an hour', 'swelling', 'fatigue'], treatments: ['early DMARD therapy', 'NSAID and short steroid for symptoms', 'specialist rheumatology'], redFlags: ['septic joint', 'cervical myelopathy', 'systemic vasculitis'] },
  { id: 'M72', name: 'Plantar fasciitis', icd10: 'M72.2', cks: 'plantar-fasciitis', category: 'Musculoskeletal', symptoms: ['heel pain', 'worse on first steps in the morning', 'pain on palpation of the heel', 'worse after activity'], treatments: ['stretching and supportive footwear', 'analgesia', 'orthotics'], redFlags: ['bilateral with systemic features', 'numbness (nerve entrapment)'] },
  { id: 'M75', name: 'Shoulder pain (rotator cuff / frozen shoulder)', icd10: 'M75.00', cks: 'shoulder-pain', category: 'Musculoskeletal', symptoms: ['shoulder pain', 'restricted movement', 'pain on overhead activity', 'night pain'], treatments: ['analgesia', 'physiotherapy', 'corticosteroid injection if needed'], redFlags: ['trauma with deformity', 'mass or systemic symptoms', 'red hot joint'] },
  { id: 'M35', name: 'Polymyalgia rheumatica', icd10: 'M35.3', cks: 'polymyalgia-rheumatica', category: 'Rheumatology', symptoms: ['bilateral shoulder and hip girdle pain', 'morning stiffness', 'over age 50', 'raised inflammatory markers'], treatments: ['low-dose oral corticosteroid with good response', 'gradual taper', 'monitor'], redFlags: ['headache, jaw claudication or visual symptoms (giant cell arteritis)'] },
  { id: 'M79', name: 'Fibromyalgia', icd10: 'M79.7', cks: 'fibromyalgia', category: 'Rheumatology', symptoms: ['widespread pain', 'fatigue', 'unrefreshing sleep', 'cognitive difficulty', 'normal inflammatory markers'], treatments: ['education and graded exercise', 'sleep and pace management', 'consider neuropathic agents'], redFlags: ['features suggesting inflammatory or systemic disease', 'focal neurology'] },

  // Mental health / sleep
  { id: 'G47.0', name: 'Insomnia', icd10: 'G47.00', cks: 'insomnia', category: 'Mental health', symptoms: ['difficulty falling or staying asleep', 'daytime fatigue', 'poor concentration', 'irritability'], treatments: ['sleep hygiene and CBT for insomnia', 'short-term hypnotic only if needed', 'treat underlying causes'], redFlags: ['symptoms of depression or sleep apnoea', 'thoughts of self-harm'] },
  { id: 'F41.0', name: 'Panic disorder', icd10: 'F41.0', cks: 'panic-disorder', category: 'Mental health', symptoms: ['recurrent panic attacks', 'palpitations', 'breathlessness', 'fear of dying', 'avoidance'], treatments: ['CBT', 'consider SSRI', 'breathing and self-help techniques'], redFlags: ['chest pain or arrhythmia needing cardiac assessment', 'suicidal ideation'] },

  // Infectious / general
  { id: 'B27', name: 'Infectious mononucleosis (glandular fever)', icd10: 'B27.90', cks: 'glandular-fever-infectious-mononucleosis', category: 'Infectious disease', symptoms: ['sore throat', 'fever', 'marked fatigue', 'cervical lymphadenopathy', 'tonsillar exudate'], treatments: ['rest and fluids', 'analgesia', 'avoid contact sport (splenic rupture risk)', 'avoid amoxicillin'], redFlags: ['airway compromise from tonsillar swelling', 'left upper quadrant pain (splenic rupture)'] },
  { id: 'B80', name: 'Threadworm (enterobiasis)', icd10: 'B80', cks: 'threadworm', category: 'Infectious disease', symptoms: ['perianal itch worse at night', 'visible white threads', 'disturbed sleep', 'common in children'], treatments: ['single-dose anthelmintic for whole household', 'hygiene measures', 'wash bedding'], redFlags: ['persistent symptoms despite treatment', 'weight loss (alternative diagnosis)'] },
]

async function main() {
  const now = new Date().toISOString()
  const items: ConditionEntry[] = E.map((s) => ({
    conditionId: s.id, name: s.name, icd10Code: s.icd10, category: s.category,
    symptoms: s.symptoms, treatments: s.treatments, redFlags: s.redFlags,
    citations: [{ id: `${s.id}-cks`, title: `${s.name} — NICE Clinical Knowledge Summaries`, source: 'NICE CKS', url: `https://cks.nice.org.uk/topics/${s.cks}/`, identifier: 'NICE CKS' }],
    source: 'curated', prior: 1.0, updatedAt: now,
  }))
  for (let i = 0; i < items.length; i += 25) {
    await doc.send(new BatchWriteCommand({ RequestItems: { [TABLE]: items.slice(i, i + 25).map((Item) => ({ PutRequest: { Item } })) } }))
  }
  console.log(`Done. ${items.length} extended conditions written.`)
}

main().catch((e) => { console.error('import-extended failed:', e?.message || e); process.exit(1) })
